// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl6-9S9mqz3ZZUSyNAq9F7goEihbVcQlM',
    appId: '1:924470608982:web:33fe1cd90b888094e9e7f7',
    messagingSenderId: '924470608982',
    projectId: 'reto-lectura-app',
    authDomain: 'reto-lectura-app.firebaseapp.com',
    storageBucket: 'reto-lectura-app.firebasestorage.app',
    measurementId: 'G-3BVHK1ZFTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANffOf7OC4-spg0jFz43WttNSScj71l0c',
    appId: '1:924470608982:android:a1309f60db12c050e9e7f7',
    messagingSenderId: '924470608982',
    projectId: 'reto-lectura-app',
    storageBucket: 'reto-lectura-app.firebasestorage.app',
  );
}
